#!/bin/bash -l
#PBS -N exa_test
#PBS -l nodes=2:ppn=32
#PBS -l walltime=00:30:00
#PBS -M  <login>@i10.informatik.uni-erlangen.de -m abe
#PBS -q normal

### start of jobscript

. /etc/profile.d/modules.sh

module load openmpi
module load gcc

cd /home/stud/ug30owag/Documents/GMRF_exa

make clean && time make -j
mpirun -np 36 -npernode 18 ./exastencils
