#!/bin/bash -l
#PBS -N _ADD_NAME_
#PBS -l nodes=2	:ppn=32
#PBS -l walltime=00:30:00
#PBS -M _ADD_MAIL_ -m abe
#PBS -o $PBS_JOBNAME.out -e $PBS_JOBNAME.out
#PBS -q normal

### start of jobscript

. /etc/profile.d/modules.sh

module load openmpi
module load gcc/4.8.2

cd _PATH_OF_PROJECT_

make clean && time make -j
mpirun -np 36 -npernode 18 ./exastencils
